name: Release

on:
  workflow_dispatch:

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: pnpm ci
      - run: pnpm test
      - run: pnpm -r publish
